### PR TITLE
Added forum heading and followAfterReply

### PR DESCRIPTION
**Pull request by petermein**

### CODE REVIEW

**Comment by franzliedke** [comment]
If I'm not mistaken, the keys do not match up with the ones in https://github.com/flarum/subscriptions/pull/6.

**Comment by petermein** [comment]
Correct, i changed the path to match the files.

**Comment by tobscure** [comment]
Not sure this should've been merged until after https://github.com/flarum/subscriptions/pull/6 has been... I made a suggestion in https://github.com/flarum/core/issues/310#issuecomment-166166860 to put the switch under the "notifications" fieldset which would make the `forum_heading` translation unused, but it hasn't been implemented yet. Oh well, we'll get there :P

**Comment by franzliedke** [comment]
Sorry about this. :(

**Pull request merged**
